Data:
  functional_data: "./data/hr_train.csv" #EDITED Moritz
  morphological_data: "./data/lr_train.csv" #EDITED Moritz

Seed:
  seed: 11


Wandb:
  use_wandb: False
  key:


Sampling:
  load_path_f_1: "./results/Diffusion_Train/fold_1.ckpt"
  load_path_f_2: "./results/Diffusion_Train/fold_2.ckpt"
  load_path_f_3: "./results/Diffusion_Train/fold_3.ckpt"
  guidance: 0.5
  save_dir: './results/Diffusion_Sample'
  source_dim: 160 #EDITED Moritz
  batch_size: 16
  n_feat: 48
  three_layers: True




Diffusion:
  three_layers: True
  accelerator: 'gpu'
  batch_size: 16
  epochs: 100
  save_dir: './results/Diffusion_Train'
  dropout_prob: 0.2
  fast_dev_run: False
  n_feat: 48
  source_dim: 160 #EDITED Moritz
  target_dim: 268  #EDITED Moritz

  load_dir_1: './results/Diffusion_Train/fold_1.ckpt'
  load_dir_2: './results/Diffusion_Train/fold_2.ckpt'
  load_dir_3: './results/Diffusion_Train/fold_3.ckpt'

  beta1: 0.0001
  beta2: 0.02

  n_T: 400

  lr: 0.0005




